---
title: Finesse Records
timezone: UTC
collections:
  artists:
    title: Artists
    output: false
  releases:
    title: Releases
    output: true
  clients:
    title: Clients
    output: false
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
  team:
    title: Team
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: clients
  values:
    image:
    is-home-featured:
    is-artist-and-label-press-featured:
    is-events-press-featured:
    is-daytime-radio-featured:
    is-specialist-radio-and-club-featured:
    is-streaming-promotion-featured:
    is-client-featured:
    website:
    facebook:
    twitter:
    instagram:
    spotify:
    soundcloud:
    youtube:
    apple:
- scope:
    path: ''
    type: services
  values:
    service:
    subtitle:
    excerpt:
- scope:
    path: ''
    type: team
  values:
    image:
    job-title:
    is-featured:
    email:
url: https://www.finesse.mx
description: Finesse Records bla bla bla...
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
company: The True Finesse Records
email:
google_site_verification:
analytics: UA-91478170-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  facebook: https://www.facebook.com/FinesseRecords
  instagram: https://www.instagram.com/finesserecords/
  twitter: https://twitter.com/finessemx
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
imgix:
  source: finesse.imgix.net
